package com.github.zjjfly.template.model;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.Hibernate;

import java.util.Objects;
import java.util.UUID;

/**
 * @author <a href="https://github.com/zjjfly"/>zjjfly</a>
 */
@MappedSuperclass
@Getter
@Setter
@ToString(callSuper = true)
public class AutoGeneratedIdEntity<U> extends BaseEntity<U> {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private UUID id;

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }

        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) {
            return false;
        }
        AutoGeneratedIdEntity that = (AutoGeneratedIdEntity) o;
        return id != null && Objects.equals(id, that.id) && Objects.equals(version, that.version);
    }

    @Override
    public int hashCode() {
        final int prime = 59;
        int result = 1;
        result = prime * result + ((id == null) ? 43 : id.hashCode()) + (version == null ? 47 : version.hashCode());
        return result;
    }
}
