server:
  tomcat:
    threads:
      max: 100
      min-spare: 5
    max-connections: 1000
    accept-count: 100
  port: 8088
  servlet:
    context-path: /api
  max-http-request-header-size: 65536

spring:
  application:
    name: spring-template
  messages:
    basename: i18n/messages
    cache-duration: 3600
    fallback-to-system-locale: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 60000
      validation-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.order_by.default_null_ordering: last
  flyway:
    #数据库存在表时，自动使用设置的基线版本（baseline-version），数据库不存在表时，即使设置了，也会从第一个版本开始执行，默认值为false
    baseline-on-migrate: true
    #基线版本号，baseline-on-migrate为true时小于等于此版本号的脚本不会执行，默认值为1
    baseline-version: 1.0.0
    #设置为false会删除指定schema下所有的表，生产环境务必禁用，spring中该参数默认是false，需要手动设置为true
    clean-disabled: true
    #sql脚本存放位置，允许设置多个location，用英文逗号分割，默认值为classpath:db/migration
    locations: classpath:db/migration
    #是否替换sql脚本中的占位符，占位符默认是${xxx},默认是替换，如果不需要替换，可以设置为false
    placeholder-replacement: false
    #脚本名称的统一前缀，用于filter要执行的脚本
    sql-migration-prefix: V
    #版本和后面的描述之间的分隔符
    sql-migration-separator: __
    #记录flyway执行情况的表
    table: flyway_schema_history
    fail-on-missing-locations: true
    #脚本的后缀，用于filter要执行的脚本
    sql-migration-suffixes: .sql


  profiles:
    active: @active-profile@

logging:
  level:
    net.ttddyy.dsproxy.listener: DEBUG

error:
  handling:
    full-stacktrace-http-statuses[0]: 5xx


springdoc:
  swagger-ui:
    #开启swagger-ui文档展示
    enabled: true
    #UI访问路径
    path: /swagger-ui.html
    #标签排序方式
    tags-sorter: alpha
    #操作排序方式
    operations-sorter: alpha
  api-docs:
    #开启OpenAPI展示
    enabled: true
    #OpenAPI JSON路径
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  #关闭文档缓存
  cache:
    disabled: false
  #显示actuator端点
  show-actuator: false
  #推荐保持默认，显示结构化参数
  default-flat-param-object: true
  #允许在文档中展示Spring MVC的ModelAndView返回类型
  model-and-view-allowed: true
  #推荐关闭以确保文档精确性
  override-with-generic-response: false
